import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MdArrowBackIos } from "react-icons/md";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function K3Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <main
        className={`w-md font-sans grid  min-h-screen pb-20 p-4 text-slate-700`}
      >
        {children}
      </main>
   
  );
}
