import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MdArrowBackIos } from "react-icons/md";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function K3Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <main
        className={`w-md font-sans grid justify-items-center min-h-screen pb-20 p-4 bg-[#154D71] text-[#FFF9AF]`}
      >
        <header className="w-full">
            <div className="flex gap-6">
            <button className="hover:bg-[#FFF9AF] hover:text-[#154D71]">
                <MdArrowBackIos/>
            </button>
            <h2>Title</h2>
            </div>
            
        </header>
        {children}
      </main>
   
  );
}
